version: 2

models:
  - name: stg_aih
    description: "Modelo de staging para os dados brutos da tabela AIH, aplicando limpeza e padronização mínima para análises posteriores."
    columns:
      - name: uf
        description: "Unidade federativa (UF) do atendimento hospitalar."
        tests:
          - not_null
      
      - name: ano_competencia
        description: "Ano da competência do registro."
        tests:
          - not_null
          - accepted_values:
              values: [2020, 2021, 2022, 2023, 2024]

      - name: mes_competencia
        description: "Mês da competência do registro."
        tests:
          - not_null
          - accepted_values:
              values: [1,2,3,4,5,6,7,8,9,10,11,12]

      - name: numero_aih
        description: "Número único da AIH (Autorização de Internação Hospitalar)."
        tests:
          - not_null
          - unique

      - name: nasc
        description: "Data de nascimento do paciente."
        tests:
          - not_null

      - name: sexo
        description: "Sexo do paciente."
        tests:
          - not_null
          - accepted_values:
              values: ['0','1','3']

      - name: dt_inter
        description: "Data de internação."
        tests:
          - not_null

      - name: dt_saida
        description: "Data de saída da internação."
        tests:
          - not_null

      - name: qt_diarias
        description: "Quantidade de diárias."
        tests:
          - not_null

      - name: idade
        description: "Idade do paciente."
        tests:
          - not_null

      - name: val_tot
        description: "Valor total."
        tests:
          - not_null
