version: 2

models:
  - name: stg_aih
    description: Modelo de staging para os dados de Autorização de Internação Hospitalar (AIH).
    columns:
      - name: numero_aih
        description: Número único da AIH.
        tests:
          - unique
          - not_null

      - name: data_internacao
        description: Data de início da internação.
        tests:
          - not_null
      
      - name: data_saida
        description: Data de saída da internação.
        tests:
          - not_null

      - name: cnes_id
        description: Identificador do hospital (CNES).
        tests:
          - not_null

      - name: morte
        description: Indica se o paciente foi a óbito (1) ou não (0).
        tests:
          - accepted_values:
              values: [1, 0]
  